mykey = "petclinic-rancher"
ami = "ami-08982f1c5bf93d976"
region = "us-east-1"
instance_type = "t3a.medium"
nexus_server_secgr = "petclinic-nexus-server-secgr"
nexus-server-tag = "Nexus Server of Petclinic"
